# Generated by Django 5.2.14 on 2026-06-27 15:06

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_episode_item_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="AnimeSeriesLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                ("is_extra", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalAnimeSeries",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical anime series",
                "verbose_name_plural": "historical anime seriess",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="app_item_media_type_valid",
        ),
        migrations.AlterField(
            model_name="item",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("animeseries", "Anime Series"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Boardgame"),
                ],
                default="movie",
                max_length=15,
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "media_type__in",
                        [
                            "tv",
                            "season",
                            "episode",
                            "movie",
                            "anime",
                            "animeseries",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                        ],
                    )
                ),
                name="app_item_media_type_valid",
            ),
        ),
        migrations.AddField(
            model_name="animeseries",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.item"
            ),
        ),
        migrations.AddField(
            model_name="animeseries",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="anime",
            name="related_series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anime_seasons",
                to="app.animeseries",
            ),
        ),
        migrations.AddField(
            model_name="animeserieslink",
            name="anime_item",
            field=models.ForeignKey(
                limit_choices_to={"media_type": "anime"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series_memberships",
                to="app.item",
            ),
        ),
        migrations.AddField(
            model_name="animeserieslink",
            name="series_item",
            field=models.ForeignKey(
                limit_choices_to={"media_type": "animeseries"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series_anime",
                to="app.item",
            ),
        ),
        migrations.AddField(
            model_name="historicalanimeseries",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="animeseries",
            constraint=models.UniqueConstraint(
                fields=("user", "item"), name="app_animeseries_unique_item_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="animeserieslink",
            constraint=models.UniqueConstraint(
                fields=("series_item", "anime_item"),
                name="app_animeserieslink_unique_series_anime",
            ),
        ),
    ]
