# Generated by Django 5.2.14 on 2026-06-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_anime_series"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeSeriesRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("alternative_version", "Alternative Version"),
                            ("alternative_setting", "Alternative Setting"),
                            ("adaptation", "Adaptation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "from_series",
                    models.ForeignKey(
                        limit_choices_to={"media_type": "animeseries"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_from",
                        to="app.item",
                    ),
                ),
                (
                    "to_series",
                    models.ForeignKey(
                        limit_choices_to={"media_type": "animeseries"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_to",
                        to="app.item",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_series", "to_series"),
                        name="app_animeseriesrelation_unique",
                    )
                ],
            },
        ),
    ]
