# Generated by Django 5.2.14 on 2026-06-29 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0063_anime_series_relation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode_number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("aired", models.DateTimeField(blank=True, null=True)),
                ("img", models.URLField(blank=True, max_length=500, null=True)),
                ("is_special", models.BooleanField(default=False)),
                (
                    "anime_item",
                    models.ForeignKey(
                        limit_choices_to={"media_type": "anime"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anime_episodes",
                        to="app.item",
                    ),
                ),
            ],
            options={
                "ordering": ["episode_number"],
                "unique_together": {("anime_item", "episode_number")},
            },
        ),
        migrations.CreateModel(
            name="SimklMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simkl_id", models.IntegerField()),
                ("cached_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.OneToOneField(
                        limit_choices_to={"media_type": "anime"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simkl_mapping",
                        to="app.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WatchedAnimeEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_episodes",
                        to="app.anime",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watches",
                        to="app.animeepisode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("anime", "episode")},
            },
        ),
    ]
