# Generated by Django 5.2.14 on 2026-06-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_anime_episodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="animeserieslink",
            name="total_episodes",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
