# Generated by Django 5.2.14 on 2026-06-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_anime_series"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0055_user_jellyfin_mark_events"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="last_search_type_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="last_search_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("animeseries", "Anime Series"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Boardgame"),
                ],
                default="tv",
                max_length=15,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "last_search_type__in",
                        [
                            "tv",
                            "movie",
                            "anime",
                            "animeseries",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                        ],
                    )
                ),
                name="last_search_type_valid",
            ),
        ),
    ]
