# Generated by Django 5.2.14 on 2026-07-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0055_user_jellyfin_mark_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Linked Telegram chat ID for notifications",
                max_length=32,
            ),
        ),
    ]
