# Generated by Django 5.2.14 on 2026-06-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0056_last_search_type_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="animeseries_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="animeseries_layout",
            field=models.CharField(
                choices=[("grid", "Grid"), ("table", "Table")],
                default="table",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="animeseries_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="animeseries_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
    ]
